backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "site/assets/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "english_posts"
    label: "English Posts"
    folder: "site/content/english/blog"
    create: true
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Continents", name: "continents", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "AI Generated", name: "ai_generated", widget: "boolean", default: false, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "french_posts"
    label: "French Posts"
    folder: "site/content/french/blog"
    create: true
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Continents", name: "continents", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "AI Generated", name: "ai_generated", widget: "boolean", default: false, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "english_pages"
    label: "English Pages"
    files:
      - file: "site/content/english/_index.md"
        label: "Home"
        name: "home"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
      - file: "site/content/english/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "french_pages"
    label: "French Pages"
    files:
      - file: "site/content/french/_index.md"
        label: "Home"
        name: "home"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
      - file: "site/content/french/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
          - { label: "Body", name: "body", widget: "markdown" }
