################################### English language #####################################
[en]
label = "En"
locale = "en-US"
contentDir = "content/english"
weight = 1


################################### French language #####################################
[fr]
label = "Fr"
locale = "fr-FR"
contentDir = "content/french"
weight = 2
