############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "à propos"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Pages du blog"
url = "blog/post-1/"

[[main]]
parent = "Pages"
name = "Catégories"
url = "categories/travel"
