############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "à propos"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Catégories"
url = "categories/"
weight = 5

[[main]]
name = "Carte"
url = "travel-map/"
weight = 6
