############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Categories"
url = "categories/"
weight = 5

[[main]]
name = "Travel Map"
url = "travel-map/"
weight = 6
